# Generated by Django 4.2 on 2023-05-09 19:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0002_stablerecord_request_data_stablerecord_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablerecord',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=8),
        )
    ]
