# Generated by Django 4.2 on 2023-05-09 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


def populate_image_urls(apps, schema_editor):
    StableRecord = apps.get_model('stable', 'StableRecord')

    for el in StableRecord.objects.all():
        el.image_urls = el.response_data['output']
        el.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0003_stablerecord_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablerecord',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, null=True, size=8),
        ),
        migrations.RunPython(populate_image_urls)
    ]
