# Generated by Django 4.2 on 2023-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0004_alter_stablerecord_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablerecord',
            name='type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
