# Generated by Django 4.2 on 2023-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
